[[durable_objects.bindings]]
compatibility_date = "2025-06-08"
name = "CHAT_ROOM"
main = "worker.js"
class_name = "ChatRoom"

[[kv_namespaces]]
binding = "CHAT_LOG"
id = "42d0ad2b23bd41bca7d5c2af7dcb6f18"
